services:
  streamx-bot:
    container_name: streamXBot
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - "${PORT:-8000}:${PORT:-8000}"

    volumes:
      - ./.env:/app/.env:ro
      - ./cookies:/app/cookies
      - ./stream_media:/app/stream_media

    restart: on-failure