import type { Track, LyricLine } from '@/schemas/track'
import type { Album } from '@/schemas/album'
import type { Artist } from '@/schemas/artist'

export const MOCK_TRACKS: Track[] = [
  {
    id: 'track-1',
    title: 'Midnight Reverie',
    artist: 'Luna Horizon',
    album: 'Celestial Drift',
    album_id: 'album-1',
    duration_sec: 218,
    cover_url: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=500&auto=format&fit=crop&q=80',
    stream_url: 'https://cdn.freesound.org/previews/612/612095_5674468-lq.mp3',
    liked: true,
    sampling_rate_hz: 48000,
    type: 'FLAC',
  },
  {
    id: 'track-2',
    title: 'Neon Skyline',
    artist: 'Solaris',
    album: 'Neon Horizons',
    album_id: 'album-2',
    duration_sec: 194,
    cover_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=80',
    stream_url: 'https://cdn.freesound.org/previews/612/612092_5674468-lq.mp3',
    liked: false,
    sampling_rate_hz: 44100,
    type: 'MP3',
  },
  {
    id: 'track-3',
    title: 'Echoes in the Rain',
    artist: 'Echo Drift',
    album: 'Ethereal Echoes',
    album_id: 'album-3',
    duration_sec: 245,
    cover_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80',
    stream_url: 'https://cdn.freesound.org/previews/612/612087_5674468-lq.mp3',
    liked: true,
    sampling_rate_hz: 96000,
    type: 'FLAC',
  },
  {
    id: 'track-4',
    title: 'Synthetic Aurora',
    artist: 'Vanguard',
    album: 'Cybernetic Dreams',
    album_id: 'album-4',
    duration_sec: 182,
    cover_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=80',
    stream_url: 'https://cdn.freesound.org/previews/530/530415_11239611-lq.mp3',
    liked: false,
    sampling_rate_hz: 48000,
    type: 'AAC',
  },
  {
    id: 'track-5',
    title: 'Velvet Sunset',
    artist: 'Nova Bloom',
    album: 'Acoustic Soul',
    album_id: 'album-5',
    duration_sec: 231,
    cover_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=80',
    stream_url: 'https://cdn.freesound.org/previews/612/612095_5674468-lq.mp3',
    liked: true,
    sampling_rate_hz: 44100,
    type: 'MP3',
  },
  {
    id: 'track-6',
    title: 'Starlight Mirage',
    artist: 'Luna Horizon',
    album: 'Celestial Drift',
    album_id: 'album-1',
    duration_sec: 204,
    cover_url: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=500&auto=format&fit=crop&q=80',
    stream_url: 'https://cdn.freesound.org/previews/612/612092_5674468-lq.mp3',
    liked: false,
    sampling_rate_hz: 48000,
    type: 'FLAC',
  },
  {
    id: 'track-7',
    title: 'Pulse of Metropolis',
    artist: 'Solaris',
    album: 'Neon Horizons',
    album_id: 'album-2',
    duration_sec: 260,
    cover_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=80',
    stream_url: 'https://cdn.freesound.org/previews/612/612087_5674468-lq.mp3',
    liked: false,
    sampling_rate_hz: 44100,
    type: 'AAC',
  },
  {
    id: 'track-8',
    title: 'Whispering Winds',
    artist: 'Kairo',
    album: 'Serenade of Silence',
    album_id: 'album-6',
    duration_sec: 175,
    cover_url: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=500&auto=format&fit=crop&q=80',
    stream_url: 'https://cdn.freesound.org/previews/530/530415_11239611-lq.mp3',
    liked: true,
    sampling_rate_hz: 96000,
    type: 'FLAC',
  },
]

export const MOCK_ALBUMS: Album[] = [
  {
    id: 'album-1',
    title: 'Celestial Drift',
    artist: 'Luna Horizon',
    artist_id: 'artist-1',
    cover_url: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=500&auto=format&fit=crop&q=80',
    year: 2025,
    track_count: 8,
  },
  {
    id: 'album-2',
    title: 'Neon Horizons',
    artist: 'Solaris',
    artist_id: 'artist-2',
    cover_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=80',
    year: 2024,
    track_count: 10,
  },
  {
    id: 'album-3',
    title: 'Ethereal Echoes',
    artist: 'Echo Drift',
    artist_id: 'artist-3',
    cover_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80',
    year: 2025,
    track_count: 7,
  },
  {
    id: 'album-4',
    title: 'Cybernetic Dreams',
    artist: 'Vanguard',
    artist_id: 'artist-4',
    cover_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=80',
    year: 2026,
    track_count: 12,
  },
  {
    id: 'album-5',
    title: 'Acoustic Soul',
    artist: 'Nova Bloom',
    artist_id: 'artist-5',
    cover_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&auto=format&fit=crop&q=80',
    year: 2023,
    track_count: 6,
  },
  {
    id: 'album-6',
    title: 'Serenade of Silence',
    artist: 'Kairo',
    artist_id: 'artist-6',
    cover_url: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=500&auto=format&fit=crop&q=80',
    year: 2025,
    track_count: 9,
  },
]

export const MOCK_ARTISTS: Artist[] = [
  {
    id: 'artist-1',
    name: 'Luna Horizon',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    monthly_listeners: 1420000,
    bio: 'Ambient electronic producer known for spatial soundscapes and immersive synthesizers.',
  },
  {
    id: 'artist-2',
    name: 'Solaris',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    monthly_listeners: 890000,
    bio: 'Synthwave pioneer blending retro-futuristic beats with modern cinematic arrangements.',
  },
  {
    id: 'artist-3',
    name: 'Echo Drift',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80',
    monthly_listeners: 610000,
    bio: 'Organic downtempo and lo-fi textures designed for deep focus and introspection.',
  },
  {
    id: 'artist-4',
    name: 'Vanguard',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    monthly_listeners: 2150000,
    bio: 'Electronic dance and industrial hyper-pop architect pushing acoustic boundaries.',
  },
  {
    id: 'artist-5',
    name: 'Nova Bloom',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&auto=format&fit=crop&q=80',
    monthly_listeners: 430000,
    bio: 'Acoustic singer-songwriter capturing warm harmonies and tender lyricism.',
  },
  {
    id: 'artist-6',
    name: 'Kairo',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=500&auto=format&fit=crop&q=80',
    monthly_listeners: 780000,
    bio: 'Cinematic neo-classical pianist combining modular synths with delicate strings.',
  },
]

export const MOCK_LYRICS: Record<string, LyricLine[]> = {
  'track-1': [
    { time: 0, text: '[Instrumental Intro — Ambient Pads]' },
    { time: 14, text: 'Standing at the edge of quiet skies' },
    { time: 22, text: 'Watching colors fade before our eyes' },
    { time: 31, text: 'Every whisper carried by the wind' },
    { time: 40, text: 'Where the night begins and dreams descend' },
    { time: 52, text: 'In the midnight reverie, we lose the gravity' },
    { time: 64, text: 'Floating through memories of who we used to be' },
    { time: 76, text: 'No shadows, no sorrow, just endless space' },
    { time: 88, text: 'Time stands still in this secret place' },
    { time: 104, text: '[Synth Solo & Atmospheric Drop]' },
    { time: 130, text: 'Catch the starlight dancing on your skin' },
    { time: 142, text: 'Feel the rhythm pulsing from within' },
    { time: 156, text: 'In the midnight reverie, we are finally free' },
    { time: 172, text: '[Instrumental Outro Fade]' },
  ],
}

export const MOCK_MIXES = [
  {
    id: 'daily:random',
    kind: 'daily',
    title: 'Daily Mix',
    subtitle: 'A fresh rotation from across your library',
    thumbnails: MOCK_TRACKS.slice(0, 4).map((t) => t.cover_url!),
    cover_url: MOCK_TRACKS[0].cover_url!,
    endpoint: '/daily-playlist/random',
    requires_auth: false,
  },
  {
    id: 'daily:rediscover',
    kind: 'daily',
    title: 'Rediscover',
    subtitle: 'Tracks you loved and haven’t played in a while',
    thumbnails: MOCK_TRACKS.slice(2, 6).map((t) => t.cover_url!),
    cover_url: MOCK_TRACKS[2].cover_url!,
    endpoint: '/daily-playlist/rediscover',
    requires_auth: false,
  },
  {
    id: 'daily:rising',
    kind: 'daily',
    title: 'Rising',
    subtitle: 'Recently added and picking up plays',
    thumbnails: [],
    cover_url: MOCK_TRACKS[3].cover_url!,
    endpoint: '/daily-playlist/rising',
    requires_auth: false,
  },
  {
    id: 'daily:surprise',
    kind: 'daily',
    title: 'Surprise Me',
    subtitle: 'Genres you don’t usually reach for',
    thumbnails: [],
    cover_url: MOCK_TRACKS[1].cover_url!,
    endpoint: '/daily-playlist/surprise',
    requires_auth: false,
  },
]
