/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AlbumAlbumIdRouteImport } from './routes/album/$albumId'
import { Route as AlbumsIndexRouteImport } from './routes/albums/index'
import { Route as AlbumsAlbumIdRouteImport } from './routes/albums/$albumId'
import { Route as ArtistArtistIdRouteImport } from './routes/artist/$artistId'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists/$artistId'
import { Route as ExploreAlbumsRouteImport } from './routes/explore/albums'
import { Route as ExploreArtistsRouteImport } from './routes/explore/artists'
import { Route as MixMixIdRouteImport } from './routes/mix/$mixId'
import { Route as PlaylistPlaylistIdRouteImport } from './routes/playlist/$playlistId'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsLibraryRouteImport } from './routes/settings/library'
import { Route as SettingsPlaybackRouteImport } from './routes/settings/playback'
import { Route as SettingsServerRouteImport } from './routes/settings/server'
import { Route as SettingsShortcutsRouteImport } from './routes/settings/shortcuts'
import { Route as TopicNameRouteImport } from './routes/topic/$name'
import { Route as TrackTrackIdRouteImport } from './routes/track/$trackId'
import { Route as SharePlaylistPlaylistIdRouteImport } from './routes/share/playlist/$playlistId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumIdRoute = AlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdRoute = AlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistArtistIdRoute = ArtistArtistIdRouteImport.update({
  id: '/artist/$artistId',
  path: '/artist/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreAlbumsRoute = ExploreAlbumsRouteImport.update({
  id: '/explore/albums',
  path: '/explore/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreArtistsRoute = ExploreArtistsRouteImport.update({
  id: '/explore/artists',
  path: '/explore/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const MixMixIdRoute = MixMixIdRouteImport.update({
  id: '/mix/$mixId',
  path: '/mix/$mixId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdRoute = PlaylistPlaylistIdRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLibraryRoute = SettingsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPlaybackRoute = SettingsPlaybackRouteImport.update({
  id: '/playback',
  path: '/playback',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsServerRoute = SettingsServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => SettingsRoute,
} as any)
const TopicNameRoute = TopicNameRouteImport.update({
  id: '/topic/$name',
  path: '/topic/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTrackIdRoute = TrackTrackIdRouteImport.update({
  id: '/track/$trackId',
  path: '/track/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const SharePlaylistPlaylistIdRoute = SharePlaylistPlaylistIdRouteImport.update({
  id: '/share/playlist/$playlistId',
  path: '/share/playlist/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/explore/albums': typeof ExploreAlbumsRoute
  '/explore/artists': typeof ExploreArtistsRoute
  '/mix/$mixId': typeof MixMixIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/playback': typeof SettingsPlaybackRoute
  '/settings/server': typeof SettingsServerRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/topic/$name': typeof TopicNameRoute
  '/track/$trackId': typeof TrackTrackIdRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/share/playlist/$playlistId': typeof SharePlaylistPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/explore/albums': typeof ExploreAlbumsRoute
  '/explore/artists': typeof ExploreArtistsRoute
  '/mix/$mixId': typeof MixMixIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/playback': typeof SettingsPlaybackRoute
  '/settings/server': typeof SettingsServerRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/topic/$name': typeof TopicNameRoute
  '/track/$trackId': typeof TrackTrackIdRoute
  '/albums': typeof AlbumsIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/share/playlist/$playlistId': typeof SharePlaylistPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/explore/albums': typeof ExploreAlbumsRoute
  '/explore/artists': typeof ExploreArtistsRoute
  '/mix/$mixId': typeof MixMixIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/playback': typeof SettingsPlaybackRoute
  '/settings/server': typeof SettingsServerRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/topic/$name': typeof TopicNameRoute
  '/track/$trackId': typeof TrackTrackIdRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/share/playlist/$playlistId': typeof SharePlaylistPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/login'
    | '/search'
    | '/settings'
    | '/signup'
    | '/album/$albumId'
    | '/albums/$albumId'
    | '/artist/$artistId'
    | '/artists/$artistId'
    | '/explore/albums'
    | '/explore/artists'
    | '/mix/$mixId'
    | '/playlist/$playlistId'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/library'
    | '/settings/playback'
    | '/settings/server'
    | '/settings/shortcuts'
    | '/topic/$name'
    | '/track/$trackId'
    | '/albums/'
    | '/artists/'
    | '/settings/'
    | '/share/playlist/$playlistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/login'
    | '/search'
    | '/signup'
    | '/album/$albumId'
    | '/albums/$albumId'
    | '/artist/$artistId'
    | '/artists/$artistId'
    | '/explore/albums'
    | '/explore/artists'
    | '/mix/$mixId'
    | '/playlist/$playlistId'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/library'
    | '/settings/playback'
    | '/settings/server'
    | '/settings/shortcuts'
    | '/topic/$name'
    | '/track/$trackId'
    | '/albums'
    | '/artists'
    | '/settings'
    | '/share/playlist/$playlistId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/login'
    | '/search'
    | '/settings'
    | '/signup'
    | '/album/$albumId'
    | '/albums/$albumId'
    | '/artist/$artistId'
    | '/artists/$artistId'
    | '/explore/albums'
    | '/explore/artists'
    | '/mix/$mixId'
    | '/playlist/$playlistId'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/library'
    | '/settings/playback'
    | '/settings/server'
    | '/settings/shortcuts'
    | '/topic/$name'
    | '/track/$trackId'
    | '/albums/'
    | '/artists/'
    | '/settings/'
    | '/share/playlist/$playlistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  AlbumAlbumIdRoute: typeof AlbumAlbumIdRoute
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRoute
  ArtistArtistIdRoute: typeof ArtistArtistIdRoute
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
  ExploreAlbumsRoute: typeof ExploreAlbumsRoute
  ExploreArtistsRoute: typeof ExploreArtistsRoute
  MixMixIdRoute: typeof MixMixIdRoute
  PlaylistPlaylistIdRoute: typeof PlaylistPlaylistIdRoute
  TopicNameRoute: typeof TopicNameRoute
  TrackTrackIdRoute: typeof TrackTrackIdRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  SharePlaylistPlaylistIdRoute: typeof SharePlaylistPlaylistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId': {
      id: '/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$artistId': {
      id: '/artist/$artistId'
      path: '/artist/$artistId'
      fullPath: '/artist/$artistId'
      preLoaderRoute: typeof ArtistArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistId': {
      id: '/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/albums': {
      id: '/explore/albums'
      path: '/explore/albums'
      fullPath: '/explore/albums'
      preLoaderRoute: typeof ExploreAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/artists': {
      id: '/explore/artists'
      path: '/explore/artists'
      fullPath: '/explore/artists'
      preLoaderRoute: typeof ExploreArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mix/$mixId': {
      id: '/mix/$mixId'
      path: '/mix/$mixId'
      fullPath: '/mix/$mixId'
      preLoaderRoute: typeof MixMixIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/library': {
      id: '/settings/library'
      path: '/library'
      fullPath: '/settings/library'
      preLoaderRoute: typeof SettingsLibraryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/playback': {
      id: '/settings/playback'
      path: '/playback'
      fullPath: '/settings/playback'
      preLoaderRoute: typeof SettingsPlaybackRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/server': {
      id: '/settings/server'
      path: '/server'
      fullPath: '/settings/server'
      preLoaderRoute: typeof SettingsServerRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/shortcuts': {
      id: '/settings/shortcuts'
      path: '/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/topic/$name': {
      id: '/topic/$name'
      path: '/topic/$name'
      fullPath: '/topic/$name'
      preLoaderRoute: typeof TopicNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$trackId': {
      id: '/track/$trackId'
      path: '/track/$trackId'
      fullPath: '/track/$trackId'
      preLoaderRoute: typeof TrackTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/playlist/$playlistId': {
      id: '/share/playlist/$playlistId'
      path: '/share/playlist/$playlistId'
      fullPath: '/share/playlist/$playlistId'
      preLoaderRoute: typeof SharePlaylistPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsLibraryRoute: typeof SettingsLibraryRoute
  SettingsPlaybackRoute: typeof SettingsPlaybackRoute
  SettingsServerRoute: typeof SettingsServerRoute
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsLibraryRoute: SettingsLibraryRoute,
  SettingsPlaybackRoute: SettingsPlaybackRoute,
  SettingsServerRoute: SettingsServerRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  AlbumAlbumIdRoute: AlbumAlbumIdRoute,
  AlbumsAlbumIdRoute: AlbumsAlbumIdRoute,
  ArtistArtistIdRoute: ArtistArtistIdRoute,
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
  ExploreAlbumsRoute: ExploreAlbumsRoute,
  ExploreArtistsRoute: ExploreArtistsRoute,
  MixMixIdRoute: MixMixIdRoute,
  PlaylistPlaylistIdRoute: PlaylistPlaylistIdRoute,
  TopicNameRoute: TopicNameRoute,
  TrackTrackIdRoute: TrackTrackIdRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  SharePlaylistPlaylistIdRoute: SharePlaylistPlaylistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
